import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

import {
  CardComponent,
  FlexComponent,
  TextComponent,
} from '@english-learning/fe-ui';

@Component({
  selector: 'lib-test1-bank',
  standalone: true,
  imports: [
    CommonModule,
    FlexComponent,
    CardComponent,
    TextComponent,
  ],
  templateUrl: './test1-bank.component.html',
})
export class Test1BankComponent {
  bank = [
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
    { a: 'lorem ipsun', b: 'polski lorem ipsum' },
  ];
}
