import { Component } from '@angular/core';

import {
  BankComponent,
  BankModel,
} from '@english-learning/fe-ui';

@Component({
  selector: 'lib-test1-bank',
  standalone: true,
  imports: [BankComponent],
  templateUrl: './test1-bank.component.html',
})
export class Test1BankComponent {
  words: BankModel[] = [
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
    { english: 'lorem ipsun', polish: 'polski lorem ipsum' },
  ];
}
